name: AWS AMI using Packer Config

on:
  pull_request:
    branches: [main]

permissions:
    id-token: write # This is required for requesting the jwt
    contents: read  # This is required for actions/checkout

jobs:

  build:
    runs-on: ubuntu-latest
    name: packer
  if: github.event.pull_request.merged == true
  steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Step 2 - Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::475967084164:role/github-role
          aws-region: "us-east-1"
          
    # build artifact
      - name: Build Artifact
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "--var-file=./packer/variable.pkrvars.hcl "
          target: ./packer/aws-ami.pkr.hcl
        env:
          PACKER_LOG: 1