name: Build and Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install Dependencies
        run: npm install

      - name: Build Application
        run: npm run build

      - name: Package Artifact
        run: tar -czvf app.tar.gz dist

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: app.tar.gz
