name: Build and Deploy to EC2

on:
  push:
    branches:
      - assignment4

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install Dependencies
        run: npm install

      - name: Build Application
        run: npm run build

      - name: build zip file
        run: |
          echo "PWD: $(pwd)"
          cd ../
          zip -r webservice.zip webservice
          ls -l
          echo "PWD: $(pwd)"
          cd webservice
          echo "mkdir"; mkdir appDir
          cp ../webservice.zip appDir
          ls -l appDir
          echo $GITHUB_PATH

