name: Build AMI

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
permissions:
    id-token: write # This is required for requesting the jwt
    contents: read  # This is required for actions/checkout
jobs:
  validate:
    runs-on: ubuntu-latest
    name: packer-build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Validate AMI template
        run: |
          # Use Packer to validate the AMI template
          packer validate  -var-file=./packer/variable.pkrvars.hcl ./packer/aws-ami.pkr.hcl
        continue-on-error: true
      
      - name: Fail PR status check if template is invalid
        run: |
          if [ $? -ne 0 ]; then
            echo "AMI template is invalid. Please fix the errors and try again."
            exit 1
          fi

  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: build zip file
        run: |
          echo "PWD: $(pwd)"
          cd ../
          zip -r webapp.zip webapp
          ls -l
          echo "PWD: $(pwd)"
          cd webapp
          echo "mkdir"; mkdir appDir
          cp ../webapp.zip appDir
          ls -l appDir
          echo $GITHUB_PATH
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::475967084164:role/github-role
          aws-region: "us-east-1"
      
      - name: Create AMI
        run: |
          # Use Packer to create the AMI
          packer build  -var-file=./packer/variable.pkrvars.hcl ./packer/aws-ami.pkr.hcl
