name: AWS AMI using Packer Config
env:
  CI: true
  ssh_username: "ec2-user"
  GITHUB_REPO_PATH: ${{ github.workspace }}

on:
  pull_request:
    branches: [main]

permissions:
    id-token: write # This is required for requesting the jwt
    contents: read  # This is required for actions/checkout

jobs:

  build:
    runs-on: ubuntu-latest
    name: packer

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Step 2 - Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::475967084164:role/github-role
          aws-region: "us-east-1"
         
      - name: build zip file
        run: |
          echo "PWD: $(pwd)"
          cd ../
          zip -r webapp.zip webapp
          ls -l
          echo "PWD: $(pwd)"
          cd webapp
          echo "mkdir"; mkdir appDir
          cp ../webapp.zip appDir
          ls -l appDir
          echo $GITHUB_PATH

      - name: Initialize Packer Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: init
          target: ./packer/aws-ami.pkr.hcl


     # validate templates
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: ./packer/aws-ami.pkr.hcl

      # build artifact
      - name: Build Artifact
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "--var-file=./packer/variable.auto.pkrvars.hcl "
          target: ./packer/aws-ami.pkr.hcl
        env:
          PACKER_LOG: 1


