name: Build AMI

env:
  CI: true
  ssh_username: "ec2-user"
  GITHUB_REPO_PATH: ${{ github.workspace }}

on:
  push:
   branches: [main]
permissions:
    id-token: write # This is required for requesting the jwt
    contents: read  # This is required for actions/checkout
jobs:
  validate:
    runs-on: ubuntu-latest
    name: packer-build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: build zip file
        run: |
          echo "PWD: $(pwd)"
          cd ../
          zip -r webapp.zip webapp
          ls -l
          echo "PWD: $(pwd)"
          cd webapp
          echo "mkdir"; mkdir appDir
          cp ../webapp.zip appDir
          ls -l appDir
          echo $GITHUB_PATH

       
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ vars.DEV_ACCOUNT_ID }}:role/github-role
          aws-region: "us-east-1"
      
      - name: Build AMI
        id: ami-id
        run: |
          echo "Running packer build"
          packer build -var-file=./packer/variable.pkrvars.hcl ./packer/aws-ami.pkr.hcl
          AMI_ID=$(jq -r '.builds[-1].artifact_id' manifest.json | cut -d ":" -f2)
          echo "AMI_ID=$AMI_ID" >> $GITHUB_ENV

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ vars.DEMO_ACCOUNT_ID }}:role/github-role
          aws-region: "us-east-1"


      - name: Create Launch Template Version
        run: |
         aws ec2 create-launch-template-version --launch-template-name ${{ vars.LAUNCH_TEMPLATE_NAME }} --source-version 1 --launch-template-data '{"ImageId":"${{ env.AMI_ID }}"}'

      - name: Instance refresh using auto-scaling
        run: |
          aws autoscaling start-instance-refresh --auto-scaling-group-name=${{ vars.AUTOSCALING_GROUP_NAME }} 



       




        